export const projects = [
  {
    title: 'Crypto Verse',
    description: "Using React, React Charts, Ant Design (antd), Millify, Moment, Chart.js I was able to build a cryptocurrency app, which allow users to see all the cryptocurrency in the market, it's individual market cap, chart, price etc..",
      image: '/images/1.png',
      tags: ['React.js', 'Chart.js', 'Antd', 'Millify'],
    // source: 'https://github.com/heiscostly/Cryptocurrency-React-App',
    visit: 'https://frosty-fermat-a85f0d.netlify.app',
    id: 0,
  },
  {
    title: 'Tailorgang Academy',
    description:"Kickstart your Fashion and Design career, grow your skills, meet top designers, learn at your own pace and time.",
    image: '/images/2.png',
    tags: ['Html','Css', 'Bootstrap', 'JavaScript', 'Figma'],
    // source: 'https://www.figma.com/file/g8MhU4jwuNwzRtAbsd4UI5/Tailorgang-Academy',
    visit: 'https://academy.tailorgang.io',
    id: 1,
  },
  {
    title: 'Hooper Website',
    description: "Hopper shows you when to wait, and when to book, for both flights and hotels. Get notified the instant prices drop. Oh, and it’s free",
      image: '/images/3.png',
      tags: ['React', 'Figma'],
    // source: 'https://www.figma.com/file/9usJdFiRQ8Cblwv4jW0ZCU/Hopper.com---A-project-by-Narative-(Copy)-(Copy)-(Copy)',
    visit: 'https://pensive-leavitt-867a00.netlify.app',
    id: 2,
  },
  {
    title: 'Gramfree',
    description: "GramFree is a blockchain-based digital project developed to be fast, safe, scalable and capable of processing millions of transactions per second",
    image: '/images/4.png',
    tags: ['Html', 'Css', 'Javascript'],
    // source: 'https://gramfree.net',
    visit: 'https://silly-heyrovsky-bea356.netlify.app',
    id: 3,
  },
  {
    title: 'All in the Mind Series',
    description: "A book launching website for a client that want to launch his book.",
    image: '/images/5.png',
    tags: ['Html', 'Css', 'Javascript', 'php'],
    // source: 'Prince D. Ekwedike',
    visit: 'https://allinthemindseries.com',
    id: 3,
  },
  {
    title: 'Crutech Portal',
    description: "Get your Student Payment Code, to enable you process payments. You need only one Student Payment Code for all your payments",
    image: '/images/6.png',
    tags: ['Html', 'Css', 'Javascript', 'php'],
    // source: 'https://crutech.edu.ng',
    visit: 'https://portal.crutech.edu.ng',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Joined My School GDG(DSC)- Developer Student Club sponsored by Google', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Landed My First Tech Job', },
];